export const coursesData = [
  {
    id: 1,
    thumbnail: "/images/courses-graphic-designer-101.jpg",
    name: "Graphic Designer 101",
    level: "All Levels",
    chapters: [
      {
        id: 1,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Introduction",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Basic Concept",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Getting Started",
      },
      {
        id: 2,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Backend",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Frontend",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Bagian Praktik",
      },
    ],
    description:
      "MERN Stack adalah bagian dari Full-Stack Web Developer yang difokuskan kepada JavaScript (Full-Stack JavaScript Developer). M untuk MongoDB, E untuk ExpressJS, R untuk ReactJS, dan N untuk NodeJS. Kalian akan mempelajari semua hal tersebut pada kelas ini. Tapi bukan hanya sekedar ngoding aja namun kalian akan mulai dari bagian UI dan UX sehingga paham betul bagaimana caranya membangun suatu website yang memiliki better experience.",
    total_student: 15,
    total_videos: 1456,
    certificate: 1,
    type: "free",
    price: 0,
    images: [
      {
        id: 1,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
    ],
    mentor: {
      id: 1,
      email: "mentor@example.com",
      name: "Aldy Mentor",
      profession: "Frontend Developer",
      profile: "/images/mentor-aldy.jpg",
    },
    reviews: [
      {
        course_id: 1,
        id: 1,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
    ],
  },
  {
    id: 2,
    thumbnail: "/images/courses-start-vlogging.jpg",
    name: "Start Vlogging",
    level: "Beginner",
    chapters: [
      {
        id: 1,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Introduction",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Basic Concept",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Getting Started",
      },
      {
        id: 2,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Backend",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Frontend",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Bagian Praktik",
      },
    ],
    description:
      "MERN Stack adalah bagian dari Full-Stack Web Developer yang difokuskan kepada JavaScript (Full-Stack JavaScript Developer). M untuk MongoDB, E untuk ExpressJS, R untuk ReactJS, dan N untuk NodeJS. Kalian akan mempelajari semua hal tersebut pada kelas ini. Tapi bukan hanya sekedar ngoding aja namun kalian akan mulai dari bagian UI dan UX sehingga paham betul bagaimana caranya membangun suatu website yang memiliki better experience.",
    total_student: 15,
    total_videos: 1456,
    certificate: 1,
    type: "free",
    price: 0,
    images: [
      {
        id: 1,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
    ],
    mentor: {
      id: 1,
      email: "mentor@example.com",
      name: "Aldy Mentor",
      profession: "Frontend Developer",
      profile: "/images/mentor-aldy.jpg",
    },
    reviews: [
      {
        course_id: 1,
        id: 1,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
    ],
  },
  {
    id: 3,
    thumbnail: "/images/courses-graphic-designer-101.jpg",
    name: "Graphic Designer 101",
    level: "All Levels",
    chapters: [
      {
        id: 1,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Introduction",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Basic Concept",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Getting Started",
      },
      {
        id: 2,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Backend",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Frontend",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Bagian Praktik",
      },
    ],
    description:
      "MERN Stack adalah bagian dari Full-Stack Web Developer yang difokuskan kepada JavaScript (Full-Stack JavaScript Developer). M untuk MongoDB, E untuk ExpressJS, R untuk ReactJS, dan N untuk NodeJS. Kalian akan mempelajari semua hal tersebut pada kelas ini. Tapi bukan hanya sekedar ngoding aja namun kalian akan mulai dari bagian UI dan UX sehingga paham betul bagaimana caranya membangun suatu website yang memiliki better experience.",
    total_student: 15,
    total_videos: 1456,
    certificate: 1,
    type: "free",
    price: 0,
    images: [
      {
        id: 1,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
    ],
    mentor: {
      id: 1,
      email: "mentor@example.com",
      name: "Aldy Mentor",
      profession: "Frontend Developer",
      profile: "/images/mentor-aldy.jpg",
    },
    reviews: [
      {
        course_id: 1,
        id: 1,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          roles: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          roles: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          roles: "student",
        },
      },
    ],
  },
  {
    id: 4,
    thumbnail: "/images/courses-start-vlogging.jpg",
    name: "Start Vlogging",
    level: "Beginner",
    chapters: [
      {
        id: 1,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Introduction",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Basic Concept",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Getting Started",
      },
      {
        id: 2,
        course_id: 1,
        lessons: [
          {
            chapter_id: 1,
            id: 1,
            name: "Backend",
            video: "MiiANxRHSv4",
          },
          {
            chapter_id: 1,
            id: 2,
            name: "Frontend",
            video: "MiiANxRHSv4",
          },
        ],
        name: "Bagian Praktik",
      },
    ],
    description:
      "MERN Stack adalah bagian dari Full-Stack Web Developer yang difokuskan kepada JavaScript (Full-Stack JavaScript Developer). M untuk MongoDB, E untuk ExpressJS, R untuk ReactJS, dan N untuk NodeJS. Kalian akan mempelajari semua hal tersebut pada kelas ini. Tapi bukan hanya sekedar ngoding aja namun kalian akan mulai dari bagian UI dan UX sehingga paham betul bagaimana caranya membangun suatu website yang memiliki better experience.",
    total_student: 15,
    total_videos: 1456,
    certificate: 1,
    type: "free",
    price: 0,
    images: [
      {
        id: 1,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
      {
        id: 2,
        image: "/images/img-hero-alyssa.jpg",
      },
    ],
    mentor: {
      id: 1,
      email: "mentor@example.com",
      name: "Aldy Mentor",
      profession: "Frontend Developer",
      profile: "/images/mentor-aldy.jpg",
    },
    reviews: [
      {
        course_id: 1,
        id: 1,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          roles: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
      {
        course_id: 1,
        id: 2,
        note: "I think this is the best invesment that I ever did better than my daily lipstick or cream.",
        rating: 4,
        user_id: 2,
        users: {
          avatar: "/images/review-user-suneo.jpg",
          email: "suneo@example.com",
          id: 1,
          name: "Suneo Giant",
          profession: "student",
          role: "student",
        },
      },
    ],
  },
];
